severity = 4

[CodeLayout::ProhibitHardTabs]
allow_leading_tabs = 0
severity = 4

[CodeLayout::ProhibitTrailingWhitespace]
severity = 4

[Documentation::RequirePackageMatchesPodName]
severity = 4

[Modules::ProhibitExcessMainComplexity]
severity = 4

[Subroutines::ProhibitManyArgs]
severity = 4

[Subroutines::ProtectPrivateSubs]
severity = 4

[Variables::ProtectPrivateVars]
severity = 4

[BuiltinFunctions::ProhibitVoidGrep]
severity = 4

[BuiltinFunctions::ProhibitVoidMap]
severity = 4

[ControlStructures::ProhibitDeepNests]
severity = 4

[InputOutput::ProhibitBacktickOperators]
severity = 4

[NamingConventions::Capitalization]
severity = 4

[RegularExpressions::ProhibitCaptureWithoutTest]
severity = 4

[RegularExpressions::ProhibitFixedStringMatches]
severity = 4

[RegularExpressions::ProhibitUnusedCapture]
severity = 4

[TestingAndDebugging::RequireUseStrict]
equivalent_modules = strictures Mojo::Base Mojolicious::Lite Moo Moo::Role figaro Figaro NT

[TestingAndDebugging::RequireUseWarnings]
equivalent_modules = strictures Mojo::Base Mojolicious::Lite Moo Moo::Role figaro Figaro NT

[Subroutines::RequireFinalReturn]
severity = 3

[Subroutines::ProhibitBuiltinHomonyms]
severity = 3

[Modules::ProhibitExcessMainComplexity]
max_mccabe = 25

[InputOutput::RequireBriefOpen]
lines = 20

[ValuesAndExpressions::ProhibitVersionStrings]
severity = 1
