# https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod

requires 'perl', 'v5.26';
requires 'File::ShareDir', '1.118';
requires 'Moo', '2.005005';
requires 'strictures', '2.000006';
requires 'Test::Perl::Critic', '1.04';
requires 'Try::Tiny', '0.32';

on develop => sub {
    requires 'Dist::Zilla', '6.037';
    requires 'Dist::Zilla::PluginBundle::OYOULE', '2.1.1';
};
