# https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod

requires 'perl', 'v5.26';
requires 'Beanstalk::Client', '1.07';
requires 'Const::Fast', '0.014';
requires 'Essentials::Exception', '0.1.0';
requires 'Essentials::Script::Service', '0.1.0';
requires 'Moo', '2.005005';
requires 'Moo::Role', '2.005005';
requires 'strictures', '2.000006';
requires 'Try::Tiny', '0.32';

on build => sub {
    requires 'Dist::Zilla', '6.037';
    requires 'Dist::Zilla::PluginBundle::OYOULE', '2.1.1';
};

on test => sub {
    requires 'Beanstalk::Job', '1.07';
    requires 'Essentials::Test::Critic', '0.1.0';
    requires 'Test::MockModule', '0.180.0';
};
