# https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod

requires 'perl', 'v5.26';
requires 'Moo', '2.005005';
requires 'strictures', '2.000006';
requires 'Throwable', '1.001';

on develop => sub {
    requires 'Dist::Zilla', '6.037';
    requires 'Dist::Zilla::PluginBundle::OYOULE', '2.1.1';
};

on test => sub {
    requires 'Essentials::Test::Critic', '0.1.0';
    requires 'Test::Compile', 'v3.3.3';
    requires 'Test::Exception', '0.43';
    requires 'Test::More', '1.302219';
    requires 'Try::Tiny', '0.32';
};
